### ISSUE TITLE
ES6 to CommonJS

### ISSUE THREAD

**Issue by devlsh** [gamestdio/keycode#1]
I don't use TypeScript which is why I haven't also created a PR for this - but the keycodes file is exported via ES6 Modules, which (given I and many others don't use TS, especially server-side) means that I cannot use the module on my Node Server.

If TypeScript supports importing CommonJS modules (Not sure why there is a TypeScript build process for a single file of exports though), then I think changing the export to CommonJS will open it up to a lot more use from native Node servers.

**Comment by endel** [comment]
Thanks for reporting @oyed :) 

I've just published v2.0.0 without using `export default`, now you should be able to use normally, like:

```javascript
const Keycode = require('@gamestdio/keycode');
console.log(Keycode.ENTER);
```

Alternatively:

```typescript
import * as Keycode from "@gamestdio/keycode";
console.log(Keycode.ENTER);
```
